language: go
go:
  - 1.6

branches:
  only:
    - master

sudo: required
services:
  - docker

script:
  - go install

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t alivinco/blackflowhub .
  - docker push alivinco/blackflowhub